### ISSUE TITLE
make light sources add up when they coincide

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-lab-light-pollution-simulator#2]
If the area affected by a certain light overlaps with the area affected by another, make that area look realistically brighter.

**Comment by juancarlosfarah** [comment]
I've found this, which looks promising!

https://stackoverflow.com/questions/10060242/html5-canvas-globalcompositeoperation-for-overlaying-gradients-not-adding-up-to

**Comment by NunonuN** [comment]
When the full-shielded lamp is selected, no halo is produced.

**Comment by juancarlosfarah** [comment]
> When the full-shielded lamp is selected, no halo is produced.

I think that's correct, right @NunonuN ? To me it looks good. We're still fading the stars a bit to account for light "bouncing" from the floor, but otherwise, I'm not sure how you would want to proceed.

![image](https://user-images.githubusercontent.com/1707188/56986448-07620000-6b8b-11e9-8a56-a4fb887c4b7c.png)

**Comment by NunonuN** [comment]
I think we can close this issue, no?

**Comment by juancarlosfarah** [comment]
Yup. We can close.
