### ISSUE TITLE
add halo to Moon

### ISSUE THREAD

**Issue by NunonuN** [graasp/graasp-lab-light-pollution-simulator#28]
Make sure the halo emanating from the Moon depends on its phase and has a corresponding impact on the visibility of the surrounding stars.

**Comment by NunonuN** [comment]
I think we can adopt one of three approaches for the moon phase: (i) the phase is randomly chosen everytime we start the simulator and the user cannot change it, (ii) the simulator always starts with some fixed phase (crescent moon, for example) and clicking on it the phase is changed -- as well as the halo emanating from it -- or (iii) a combination of the previous two. Personally, I prefer the third approach.

**Comment by juancarlosfarah** [comment]
@NunonuN, why don't we start with the second approach and then we can see if we can add the randomness bit in a separate commit?
