### ISSUE TITLE
change new moon

### ISSUE THREAD

**Issue by NunonuN** [graasp/graasp-lab-light-pollution-simulator#79]
We have to find a solution to remove the New Moon from the sky while allowing users to know where it is, so they can click it and cycle through the Moon phases.
**Possible solutions**:

1. Add icon;

2. Add arrow;

3. Add dashed circumference;

4. ...

**Comment by juancarlosfarah** [comment]
I think that the two simple solutions are:

1. Moon can only switch to crescent, quarter and full phases by clicking on it. However there is a separate icon somewhere with a settings gear in the student view where you can show/hide the moon. This settings will also be the place to do other more complicated changes like switch the colour of the light bulbs, etc.
2. Just like we have some general areas where you can click and make things happen, it is also possible to click in some wide area of the sky to make the moon appear.

What do you think?

**Comment by NunonuN** [comment]
Any of the solutions seem good to me, provided we keep the four phases. I would like the user to cycle between them.
On the practical use point of view, maybe the second solution is better, since it doesn't make the user to go to the settings gear. Maybe just clicking in some region of the sky (a wide area around where it was in the beginning) makes the Moon appear again and jump to the crescent phase.

**Comment by juancarlosfarah** [comment]
@NunonuN, I think we can go for the second solution to start with, then.
